############################################################################
# Timing constraints                                                       #
############################################################################

##### PS_CLK (125 MHz) #####

##### GTP reference clocks (125 MHz) #####
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets GTPRefClk0PxCI]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets GTPRefClk1xC]

##### Clocks from PLLs (125 MHz) #####
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {PLL_Clk_in_Local}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {PLL_Clk_in_North}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {PLL_Clk_in_South}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {PLL_Clk_in_Top}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {PLL_Clk_in_Bottom}]

##### Clocks from neighbours (125 MHz) #####
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_North}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_South}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_East}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_West}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_Top}]
#create_clock -period 8.000 -waveform {0.000 4.000} [get_nets {Clk_in_Bottom}]

# Output delays
#create_clock -name clk_125 -period 8.000 [get_nets sys_clock_clk_125]
#set_output_delay 1.000 -clock [get_clocks clk_125] [get_ports Led12V5RxSO]
#set_output_delay 1.000 -clock [get_clocks clk_125] [get_ports Led12V5RxSO]
#set_output_delay 1.000 -clock [get_clocks clk_125] [get_ports Led12V5RxSO]









create_pblock pblock_PLxB.ImGnxB.MndlClc
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_PLxB.ImGnxB.MndlClc]
set_property IS_SOFT FALSE [get_pblocks pblock_PLxB.ImGnxB.MndlClc]

set_property DONT_TOUCH true [get_cells PLxB.ImGenxB.MandelCalc]

set_property MARK_DEBUG true [get_nets PLxB.ImGenxB.FifoWrEnxD]

set_false_path -from [get_pins {PLxB.ImGenxB.MandelCalc/ZbxD_reg[3]/C}] -to [get_pins {PLxB.ImGenxB.MandelCalc/IterxO_reg[10]/CE}]

set_property MARK_DEBUG true [get_nets {ClpxNumRegsAxixD[ClockxC][ClkxC]}]
set_property MARK_DEBUG true [get_nets {HdmiVgaClocksxC[VgaxC]}]
set_property MARK_DEBUG true [get_nets PLxB.ImGenxB.FifoRdEnxD]

connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ImGenxB.IterxD[0]} {PLxB.ImGenxB.IterxD[1]} {PLxB.ImGenxB.IterxD[2]} {PLxB.ImGenxB.IterxD[3]} {PLxB.ImGenxB.IterxD[4]} {PLxB.ImGenxB.IterxD[5]} {PLxB.ImGenxB.IterxD[6]} {PLxB.ImGenxB.IterxD[7]} {PLxB.ImGenxB.IterxD[8]} {PLxB.ImGenxB.IterxD[9]} {PLxB.ImGenxB.IterxD[10]} {PLxB.ImGenxB.IterxD[11]} {PLxB.ImGenxB.IterxD[12]} {PLxB.ImGenxB.IterxD[13]} {PLxB.ImGenxB.IterxD[14]} {PLxB.ImGenxB.IterxD[15]} {PLxB.ImGenxB.IterxD[16]} {PLxB.ImGenxB.IterxD[17]} {PLxB.ImGenxB.IterxD[18]} {PLxB.ImGenxB.IterxD[19]} {PLxB.ImGenxB.IterxD[20]} {PLxB.ImGenxB.IterxD[21]} {PLxB.ImGenxB.IterxD[22]} {PLxB.ImGenxB.IterxD[23]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list PLxB.ImGenxB.FifoWrEnxD]]
connect_debug_port u_ila_1/probe2 [get_nets [list PLxB.ImGenxB.FifoRdEnxD]]




set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[24]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[26]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_28]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_22]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][14]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[9]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_27]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_30]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[21]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[5]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_24]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[1]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_29]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_23]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][1]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][12]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][15]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[16]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[23]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[13]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_20]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][10]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[14]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_3]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[18]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[22]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[0]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_21]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][6]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[3]}]
set_property MARK_DEBUG false [get_nets HdmiVgaClocksxC]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][5]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[10]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[20]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[4]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_1]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[11]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_25]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_31]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][2]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][7]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[17]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[12]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_2]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][4]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[14]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][3]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][13]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][0]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[25]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[12]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_26]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[19]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][0]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[HxD][8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZIm2OutPxD[27]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/ZimN1OutPxD[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/Znorm2OutPxD[15]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_0]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][1]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][3]}]
set_property MARK_DEBUG false [get_nets {VgaPixCountersxD[VxD][14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[17]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[19]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[16]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[20]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[18]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[21]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[23]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.IterxD[22]}]

set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/state[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/state[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/state[2]}]


set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CaPixxD[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[13]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/CbPixxD[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[1]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[5]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[9]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[6]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[10]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[11]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[14]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[15]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[0]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[3]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[4]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[8]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[2]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[7]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[12]}]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[13]}]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.FinishedxS]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.RdyxS]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.StartxS_reg_n_0]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[1]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[6]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[10]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[5]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[7]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[8]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[13]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[2]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[4]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[15]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[0]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[3]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[9]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[11]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[12]}]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[14]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][1]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][3]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][4]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][5]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][9]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][10]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][12]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][7]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][4]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][8]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][11]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][15]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][6]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][8]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][11]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][15]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][2]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][6]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][9]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][13]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][2]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][13]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][14]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][5]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][10]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][12]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[HxD][14]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][0]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][1]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][3]}]
set_property MARK_DEBUG true [get_nets {PLxB.HdmixB.TxxI/VgaPixCountersxDO[VxD][7]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk125xC]
