@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 27 13:12:56 +0200 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim scalp_user_design_func_impl -key {Post-Implementation:sim_1:Functional:scalp_user_design} -tclbatch scalp_user_design.tcl -protoinst "protoinst_files/bd_c0d9.protoinst" -protoinst "protoinst_files/scalp_zynqps.protoinst" -protoinst "protoinst_files/vga_hdmi_clk_rst_system_inst_0.protoinst" -log simulate.log"
call xsim  scalp_user_design_func_impl -key {Post-Implementation:sim_1:Functional:scalp_user_design} -tclbatch scalp_user_design.tcl -protoinst "protoinst_files/bd_c0d9.protoinst" -protoinst "protoinst_files/scalp_zynqps.protoinst" -protoinst "protoinst_files/vga_hdmi_clk_rst_system_inst_0.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
