set_property SRC_FILE_INFO {cfile:C:/CochetVictorLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/CochetVictorLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports UsbVbusPwrFaultxSI]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports Pll2V5ClkuWirexCO]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports Pll2V5DatauWirexSO]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports Pll2V5LEuWirexSO]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports Pll2V5GOExSO]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports Pll2V5LDxSI]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports Pll2V5SyncxSO]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports Pll2V5ClkIn0LOSxSI]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports Pll2V5ClkIn1LOSxSI]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports HdmiTXCecxSIO]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports HdmiTXHpdxSI]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {HdmiTXPxDO[2]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports {HdmiTXNxDO[2]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M8 [get_ports {HdmiTXPxDO[1]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports {HdmiTXNxDO[1]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {HdmiTXPxDO[0]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {HdmiTXNxDO[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J7 [get_ports HdmiTXClkPxSO]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports HdmiTXClkNxSO]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {SwitchesxDI[0]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {SwitchesxDI[1]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K4 [get_ports {JoystickxDI[0]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P7 [get_ports {JoystickxDI[1]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {JoystickxDI[2]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports {JoystickxDI[3]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {JoystickxDI[4]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports IoExtIICSdaxDIO]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports IoExtIICSclxDIO]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports Led12V5RxSO]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports Led12V5GxSO]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports Led12V5BxSO]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports Led22V5RxSO]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Led22V5GxSO]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports Led22V5BxSO]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports SelfRstxRNO]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_PLxB.ImGnxB.MndlClc
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_PLxB.ImGnxB.MndlClc]
set_property IS_SOFT FALSE [get_pblocks pblock_PLxB.ImGnxB.MndlClc]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets PLxB.ImGenxB.FifoWrEnxD]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets PLxB.ImGenxB.FifoRdEnxD]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ImGenxB.IterxD[0]} {PLxB.ImGenxB.IterxD[1]} {PLxB.ImGenxB.IterxD[2]} {PLxB.ImGenxB.IterxD[3]} {PLxB.ImGenxB.IterxD[4]} {PLxB.ImGenxB.IterxD[5]} {PLxB.ImGenxB.IterxD[6]} {PLxB.ImGenxB.IterxD[7]} {PLxB.ImGenxB.IterxD[8]} {PLxB.ImGenxB.IterxD[9]} {PLxB.ImGenxB.IterxD[10]} {PLxB.ImGenxB.IterxD[11]} {PLxB.ImGenxB.IterxD[12]} {PLxB.ImGenxB.IterxD[13]} {PLxB.ImGenxB.IterxD[14]} {PLxB.ImGenxB.IterxD[15]} {PLxB.ImGenxB.IterxD[16]} {PLxB.ImGenxB.IterxD[17]} {PLxB.ImGenxB.IterxD[18]} {PLxB.ImGenxB.IterxD[19]} {PLxB.ImGenxB.IterxD[20]} {PLxB.ImGenxB.IterxD[21]} {PLxB.ImGenxB.IterxD[22]} {PLxB.ImGenxB.IterxD[23]}]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list PLxB.ImGenxB.FifoWrEnxD]]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list PLxB.ImGenxB.FifoRdEnxD]]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_28]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_22]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[3]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_27]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_30]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[15]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_24]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[5]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[11]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_29]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_23]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_20]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[9]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_3]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[8]}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_21]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets HdmiVgaClocksxC]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[14]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_1]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[4]}]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[13]}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_25]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_31]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[6]}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[0]}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[12]}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_2]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[2]}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[7]}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_26]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[1]}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.MandelCalc/RESULT[10]}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.MandelCalc/ZIM2_n_0]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[1]}]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[5]}]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[9]}]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[6]}]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[10]}]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[11]}]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[14]}]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[15]}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[0]}]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[3]}]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[4]}]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[8]}]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[2]}]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[7]}]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[12]}]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {PLxB.ImGenxB.CurrAddrWrxD_reg[13]}]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets PLxB.ImGenxB.StartxS_reg_n_0]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[1]}]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[6]}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[10]}]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[5]}]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[7]}]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[8]}]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[13]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[2]}]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[4]}]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[15]}]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[0]}]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[3]}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[9]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[11]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[12]}]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.CurrAddrRdxD_reg[14]}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets Clk125xC]
